require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'bloodlife' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
permissions_path = '../node_modules/react-native-permissions/ios'

pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
pod 'Firebase/Analytics'
# Pods for testing
pod 'Firebase/Analytics'
    # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

   # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
# react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS


  target 'bloodlifeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'bloodlife-tvOS' do
  # Pods for bloodlife-tvOS

  target 'bloodlife-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
  
